services:
   redis: 
      image: redislabs/redismod
      container_name: twitter_service_redis
      restart: unless-stopped
      tty: true
      # ports:
      #   - '6279:6379'
      networks:
        - app-network
   flask:
        build: .
        container_name: twitter_service_flask
        restart: unless-stopped
        tty: true
        ports:
            - "5100:5000"
        volumes:
            - .:/twitter_service
        depends_on:
            - redis
        networks:
          - app-network
networks:
  app-network:
    driver: bridge